<?php

use App\Http\Controllers\Api\AppPlatform\ApplicationController;
use App\Http\Controllers\Api\AppPlatform\EnvironmentController;
use App\Http\Controllers\Api\AppPlatform\EnvironmentVariableController;
use App\Http\Controllers\Api\AppPlatform\GitConnectionController;
use App\Http\Controllers\Api\AppPlatform\ProcessDefinitionController;
use App\Http\Controllers\Api\AppPlatform\ProjectController;
use App\Http\Controllers\Api\AppPlatform\SecretController;
use App\Http\Controllers\Api\Deployment\DeploymentController;
use App\Http\Controllers\Api\Deployment\ReleaseController;
use App\Http\Controllers\Api\Deployment\RemoteCommandController;
use App\Http\Controllers\Api\Deployment\RuntimeProfileController;
use App\Http\Controllers\Api\Deployment\ServerRoleProfileController;
use App\Http\Controllers\Api\Infrastructure\ClusterController;
use App\Http\Controllers\Api\Infrastructure\ProviderController;
use App\Http\Controllers\Api\Infrastructure\ServerController;
use App\Http\Controllers\Api\Networking\CertificateController;
use App\Http\Controllers\Api\Networking\DomainController;
use App\Http\Controllers\Api\Operations\AuditLogController;
use App\Http\Controllers\Api\Operations\BackupController;
use App\Http\Controllers\Api\PersonalAccessTokenController;
use App\Http\Controllers\Api\Pipeline\ArtifactController;
use App\Http\Controllers\Api\Pipeline\PipelineController;
use App\Http\Controllers\Api\Pipeline\PipelineJobController;
use App\Http\Controllers\Api\Pipeline\PipelineRunController;
use App\Http\Controllers\Api\Pipeline\RunnerController as PipelineRunnerController;
use App\Http\Controllers\Api\ServiceManagement\CacheInstanceController;
use App\Http\Controllers\Api\ServiceManagement\DatabaseInstanceController;
use App\Http\Controllers\Api\ServiceManagement\ServiceBindingController;
use App\Http\Controllers\Api\ServiceManagement\StorageBucketController;
use App\Http\Controllers\Api\SshKeyController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth.token')->prefix('v1')->name('api.')->group(function () {
    Route::apiResource('tokens', PersonalAccessTokenController::class)->only(['index', 'store', 'destroy']);
    Route::apiResource('ssh-keys', SshKeyController::class)->only(['index', 'store', 'destroy']);
    Route::apiResource('projects', ProjectController::class);
    Route::get('git-connections', [GitConnectionController::class, 'index'])->name('git-connections.index');
    Route::delete('git-connections/{gitConnection}', [GitConnectionController::class, 'destroy'])->name('git-connections.destroy');
    Route::get('database-instances', [DatabaseInstanceController::class, 'index'])->name('database-instances.index');
    Route::post('database-instances', [DatabaseInstanceController::class, 'store'])->name('database-instances.store');
    Route::get('database-instances/{databaseInstance}', [DatabaseInstanceController::class, 'show'])->name('database-instances.show');
    Route::delete('database-instances/{databaseInstance}', [DatabaseInstanceController::class, 'destroy'])->name('database-instances.destroy');
    Route::post('database-instances/{databaseInstance}/rotate-credentials', [DatabaseInstanceController::class, 'rotateCredentials'])->name('database-instances.rotate-credentials');
    Route::get('cache-instances', [CacheInstanceController::class, 'index'])->name('cache-instances.index');
    Route::post('cache-instances', [CacheInstanceController::class, 'store'])->name('cache-instances.store');
    Route::get('cache-instances/{cacheInstance}', [CacheInstanceController::class, 'show'])->name('cache-instances.show');
    Route::delete('cache-instances/{cacheInstance}', [CacheInstanceController::class, 'destroy'])->name('cache-instances.destroy');
    Route::post('cache-instances/{cacheInstance}/rotate-credentials', [CacheInstanceController::class, 'rotateCredentials'])->name('cache-instances.rotate-credentials');
    Route::get('storage-buckets', [StorageBucketController::class, 'index'])->name('storage-buckets.index');
    Route::post('storage-buckets', [StorageBucketController::class, 'store'])->name('storage-buckets.store');
    Route::get('storage-buckets/{storageBucket}', [StorageBucketController::class, 'show'])->name('storage-buckets.show');
    Route::delete('storage-buckets/{storageBucket}', [StorageBucketController::class, 'destroy'])->name('storage-buckets.destroy');
    Route::post('storage-buckets/{storageBucket}/rotate-credentials', [StorageBucketController::class, 'rotateCredentials'])->name('storage-buckets.rotate-credentials');

    Route::scopeBindings()->group(function () {
        Route::get('projects/{project}/applications', [ApplicationController::class, 'index'])->name('applications.index');
        Route::post('projects/{project}/applications', [ApplicationController::class, 'store'])->name('applications.store');
        Route::get('applications/{application}', [ApplicationController::class, 'show'])->name('applications.show');
        Route::put('applications/{application}', [ApplicationController::class, 'update'])->name('applications.update');
        Route::delete('applications/{application}', [ApplicationController::class, 'destroy'])->name('applications.destroy');
        Route::get('applications/{application}/pipelines', [PipelineController::class, 'index'])->name('pipelines.index');
        Route::post('applications/{application}/pipelines', [PipelineController::class, 'store'])->name('pipelines.store');
        Route::get('applications/{application}/artifacts', [ArtifactController::class, 'index'])->name('artifacts.index');
        Route::get('applications/{application}/environments', [EnvironmentController::class, 'index'])->name('environments.index');
        Route::post('applications/{application}/environments', [EnvironmentController::class, 'store'])->name('environments.store');
        Route::get('environments/{environment}', [EnvironmentController::class, 'show'])->name('environments.show');
        Route::put('environments/{environment}', [EnvironmentController::class, 'update'])->name('environments.update');
        Route::delete('environments/{environment}', [EnvironmentController::class, 'destroy'])->name('environments.destroy');
        Route::get('environments/{environment}/domains', [DomainController::class, 'index'])->name('domains.index');
        Route::post('environments/{environment}/domains', [DomainController::class, 'store'])->name('domains.store');
        Route::get('environments/{environment}/variables', [EnvironmentVariableController::class, 'index'])->name('environment-variables.index');
        Route::post('environments/{environment}/variables', [EnvironmentVariableController::class, 'store'])->name('environment-variables.store');
        Route::put('environments/{environment}/variables/{variable}', [EnvironmentVariableController::class, 'update'])->name('environment-variables.update');
        Route::delete('environments/{environment}/variables/{variable}', [EnvironmentVariableController::class, 'destroy'])->name('environment-variables.destroy');
        Route::get('environments/{environment}/secrets', [SecretController::class, 'index'])->name('secrets.index');
        Route::post('environments/{environment}/secrets', [SecretController::class, 'store'])->name('secrets.store');
        Route::put('environments/{environment}/secrets/{secret}', [SecretController::class, 'update'])->name('secrets.update');
        Route::delete('environments/{environment}/secrets/{secret}', [SecretController::class, 'destroy'])->name('secrets.destroy');
        Route::get('environments/{environment}/secrets/{secret}/reveal', [SecretController::class, 'reveal'])->name('secrets.reveal');
        Route::get('environments/{environment}/processes', [ProcessDefinitionController::class, 'index'])->name('processes.index');
        Route::post('environments/{environment}/processes', [ProcessDefinitionController::class, 'store'])->name('processes.store');
        Route::put('environments/{environment}/processes/{processDefinition}', [ProcessDefinitionController::class, 'update'])->name('processes.update');
        Route::delete('environments/{environment}/processes/{processDefinition}', [ProcessDefinitionController::class, 'destroy'])->name('processes.destroy');
        Route::get('environments/{environment}/service-bindings', [ServiceBindingController::class, 'index'])->name('service-bindings.index');
        Route::post('environments/{environment}/service-bindings', [ServiceBindingController::class, 'store'])->name('service-bindings.store');
        Route::delete('environments/{environment}/service-bindings/{serviceBinding}', [ServiceBindingController::class, 'destroy'])->name('service-bindings.destroy');
        Route::get('environments/{environment}/deployments', [DeploymentController::class, 'index'])->name('deployments.index');
        Route::post('environments/{environment}/deploy', [DeploymentController::class, 'store'])->name('deployments.store');
        Route::post('environments/{environment}/rollback', [DeploymentController::class, 'rollback'])->name('deployments.rollback');
        Route::get('environments/{environment}/releases', [ReleaseController::class, 'index'])->name('releases.index');
        Route::get('applications/{application}/runtime-profiles', [RuntimeProfileController::class, 'index'])->name('runtime-profiles.index');
        Route::post('applications/{application}/runtime-profiles', [RuntimeProfileController::class, 'store'])->name('runtime-profiles.store');
        Route::post('environments/{environment}/runtime-profile', [RuntimeProfileController::class, 'apply'])->name('runtime-profiles.apply');
        Route::get('environments/{environment}/server-role-profiles', [ServerRoleProfileController::class, 'index'])->name('server-role-profiles.index');
        Route::post('environments/{environment}/server-role-profiles', [ServerRoleProfileController::class, 'store'])->name('server-role-profiles.store');
        Route::get('environments/{environment}/remote-commands', [RemoteCommandController::class, 'index'])->name('remote-commands.index');
        Route::post('environments/{environment}/remote-commands', [RemoteCommandController::class, 'store'])->name('remote-commands.store');
        Route::get('servers/{server}/backups', [BackupController::class, 'index'])->name('backups.index');
        Route::post('servers/{server}/backups', [BackupController::class, 'store'])->name('backups.store');
    });

    Route::get('audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('runners', [PipelineRunnerController::class, 'index'])->name('runners.index');
    Route::post('runners', [PipelineRunnerController::class, 'store'])->name('runners.store');
    Route::get('runners/{runner}', [PipelineRunnerController::class, 'show'])->name('runners.show');
    Route::delete('runners/{runner}', [PipelineRunnerController::class, 'destroy'])->name('runners.destroy');
    Route::get('pipelines/{pipeline}', [PipelineController::class, 'show'])->name('pipelines.show');
    Route::put('pipelines/{pipeline}', [PipelineController::class, 'update'])->name('pipelines.update');
    Route::delete('pipelines/{pipeline}', [PipelineController::class, 'destroy'])->name('pipelines.destroy');
    Route::post('pipelines/{pipeline}/trigger', [PipelineController::class, 'trigger'])->name('pipelines.trigger');
    Route::get('pipelines/{pipeline}/runs', [PipelineController::class, 'runs'])->name('pipelines.runs');
    Route::get('pipeline-runs/{pipelineRun}', [PipelineRunController::class, 'show'])->name('pipeline-runs.show');
    Route::post('pipeline-runs/{pipelineRun}/cancel', [PipelineRunController::class, 'cancel'])->name('pipeline-runs.cancel');
    Route::post('pipeline-runs/{pipelineRun}/retry', [PipelineRunController::class, 'retry'])->name('pipeline-runs.retry');
    Route::get('pipeline-jobs/{pipelineJob}', [PipelineJobController::class, 'show'])->name('pipeline-jobs.show');
    Route::get('pipeline-jobs/{pipelineJob}/log', [PipelineJobController::class, 'log'])->name('pipeline-jobs.log');
    Route::get('artifacts/{artifact}', [ArtifactController::class, 'show'])->name('artifacts.show');
    Route::get('deployments/{deployment}', [DeploymentController::class, 'show'])->name('deployments.show');
    Route::post('deployments/{deployment}/cancel', [DeploymentController::class, 'cancel'])->name('deployments.cancel');
    Route::get('releases/{release}', [ReleaseController::class, 'show'])->name('releases.show');
    Route::put('runtime-profiles/{runtimeProfile}', [RuntimeProfileController::class, 'update'])->name('runtime-profiles.update');
    Route::put('server-role-profiles/{serverRoleProfile}', [ServerRoleProfileController::class, 'update'])->name('server-role-profiles.update');
    Route::get('remote-commands/{remoteCommand}', [RemoteCommandController::class, 'show'])->name('remote-commands.show');

    // Infrastructure
    Route::apiResource('providers', ProviderController::class);
    Route::post('providers/{provider}/test', [ProviderController::class, 'test'])->name('providers.test');

    Route::apiResource('servers', ServerController::class);
    Route::post('servers/{server}/bootstrap', [ServerController::class, 'bootstrap'])->name('servers.bootstrap');
    Route::post('servers/{server}/drain', [ServerController::class, 'drain'])->name('servers.drain');
    Route::post('servers/{server}/cordon', [ServerController::class, 'cordon'])->name('servers.cordon');
    Route::post('servers/{server}/activate', [ServerController::class, 'activate'])->name('servers.activate');

    Route::apiResource('clusters', ClusterController::class);
    Route::post('clusters/{cluster}/nodes', [ClusterController::class, 'addNode'])->name('clusters.add-node');
    Route::delete('clusters/{cluster}/nodes/{server}', [ClusterController::class, 'removeNode'])->name('clusters.remove-node');
    Route::put('clusters/{cluster}/nodes/{server}', [ClusterController::class, 'updateNode'])->name('clusters.update-node');
    Route::delete('domains/{domain}', [DomainController::class, 'destroy'])->name('domains.destroy');
    Route::post('domains/{domain}/verify', [DomainController::class, 'verify'])->name('domains.verify');
    Route::get('domains/{domain}/certificate', [CertificateController::class, 'show'])->name('domains.certificate.show');
    Route::post('backups/{backup}/restore', [BackupController::class, 'restore'])->name('backups.restore');
});
